# DONT PUT SENSITIVE INFORMATION IN HERE! COPY IT TO config.yml AND THEN CHANGE IT!
defaults: &defaults
  secret: d1e4e6a100e3d2e2900bbdfef6fad6e0fa748f08b74feda7c9219ddb0afec87634d2e3658d16733d00a8ac8eff6f54c5ca14ca289a6f62c11cd48493aa88956f

development:
  <<: *defaults
  port: 3000

test:
  <<: *defaults
  port: 3100

staging:
  <<: *defaults
  port: 3001
